__________________________________________________________________________________________________
RecurDyn2023 [Windows x64 System 10.1.11516.0] Analysis message file.
Copyright (C) 1997 - 2022 FunctionBay, Inc. All rights reserved.

RMD file: Ring - Cube - Centric Collision.rmd [Model Name: Model3]

_________________________________________________________________________________________________
System Configuration Information
    No. of Generalized Coordinate                   = 6
    No. of Generalized Velocity                     = 6
    No. of Rigid Body                               = 2
    No. of Geo Contact                              = 1

Kinematic Degree of Freedom         = 6

Total array size                    = 3929
Total memory size for array         = 0 MB

Success Process: Array Structure Construction

_________________________________________________________________________________________________
Redundant Constraint Information
    There is no redundant constraint

_________________________________________________________________________________________________
RecurDyn/SOLVER Information
    DLL type Solver for Windows 64 Bit
    No. of CPU Thread = 4
    Save Solver Animation File(RAN) Option is turned on
    C:\Program Files\FunctionBay, Inc\RecurDyn 2023\Bin\Solver\Slvcore.dll
    C:\Program Files\FunctionBay, Inc\RecurDyn 2023\Bin\Solver\Cuser.dll

_________________________________________________________________________________________________
Analysis Information
    Dynamic Analysis
    End Time                       = 1.000000000000000
    Step                           = 1000
    Plot Multiplier Step Factor    = 1
    Maximum Time Step              = 1.0E-03
    Initial Time Step              = 1.0E-06
    Error Tolerance                = 5.0E-03

_________________________________________________________________________________________________
Information of starting time
    Starting Time/Date     = 17:16:0 / 2026.6.13

_________________________________________________________________________________________________
Integrator Information
     Advanced Hybrid Implicit Integrator :: LDLT
        Numerical Damping          = 1.000000
        Linear Solver For MBD      = DENSE

_________________________________________________________________________________________________
Analysis processing...

        TIME          STEPSIZE        A_DELNRM          NJAC      NRES      ANRF     AINTF
    6.133000E-03    5.120000E-04    0.000000E+00         100       300         0         0
    1.012530E-01    1.000000E-03    0.000000E+00         200       600         0         0
    2.012530E-01    1.000000E-03    6.799583E-03         302       911         0         0
    3.012530E-01    1.000000E-03    1.416415E-13         402      1211         0         0
    4.012530E-01    1.000000E-03    1.426073E-13         502      1511         0         0
    4.746280E-01    5.000000E-04    1.762619E-05         611      1844         1         3
    5.541280E-01    1.000000E-03    8.827292E-07         717      2163         1         6
    6.541280E-01    1.000000E-03    8.444296E-06         817      2463         1         6
    7.541280E-01    1.000000E-03    7.269390E-07         917      2763         1         6
    8.541280E-01    1.000000E-03    1.125647E-05        1017      3063         1         6
    9.541280E-01    1.000000E-03    5.498696E-07        1117      3363         1         6
    1.000000E+00    8.720000E-04    4.460205E-07        1163      3501         1         6

_________________________________________________________________________________________________
Analysis Time Information
    Starting Time/Date     = 17:16:0 / 2026.6.13
    Ending Time/Date       = 17:16:20 / 2026.6.13
    CPU Time = 19.55 Second (0 hr. 0 min 19.55 sec.)

_________________________________________________________________________________________________
Analysis is accomplished successfully

_________________________________________________________________________________________________
