__________________________________________________________________________________________________
RecurDyn2023 [Windows x64 System 10.1.11516.0] Analysis message file.
Copyright (C) 1997 - 2022 FunctionBay, Inc. All rights reserved.

RMD file: First-stage gear transmission.rmd [Model Name: Model2]

_________________________________________________________________________________________________
System Configuration Information
    No. of Generalized Coordinate                   = 2
    No. of Generalized Velocity                     = 2
    No. of Rigid Body                               = 2
    No. of Geo Contact                              = 1

Kinematic Degree of Freedom         = 1

Total array size                    = 3809
Total memory size for array         = 0 MB

Success Process: Array Structure Construction

_________________________________________________________________________________________________
Redundant Constraint Information
    There is no redundant constraint

_________________________________________________________________________________________________
RecurDyn/SOLVER Information
    DLL type Solver for Windows 64 Bit
    No. of CPU Thread = 4
    Save Solver Animation File(RAN) Option is turned on
    C:\Program Files\FunctionBay, Inc\RecurDyn 2023\Bin\Solver\Slvcore.dll
    C:\Program Files\FunctionBay, Inc\RecurDyn 2023\Bin\Solver\Cuser.dll

_________________________________________________________________________________________________
Analysis Information
    Dynamic Analysis
    End Time                       = 1.000000000000000
    Step                           = 1000
    Plot Multiplier Step Factor    = 1
    Maximum Time Step              = 1.0E-03
    Initial Time Step              = 1.0E-06
    Error Tolerance                = 5.0E-03

_________________________________________________________________________________________________
Information of starting time
    Starting Time/Date     = 21:34:21 / 2026.6.10

_________________________________________________________________________________________________
Integrator Information
     Advanced Hybrid Implicit Integrator :: LDLT
        Numerical Damping          = 1.000000
        Linear Solver For MBD      = DENSE

_________________________________________________________________________________________________
Analysis processing...

        TIME          STEPSIZE        A_DELNRM          NJAC      NRES      ANRF     AINTF
    6.133000E-03    5.120000E-04    4.346161E-05         101       304         0         0
    9.875300E-02    5.000000E-04    9.654393E-04         203       615         0         1
    1.957530E-01    1.000000E-03    1.287156E-21         305       924         0         1
    2.957530E-01    1.000000E-03    3.335264E-04         405      1227         0         1
    3.957530E-01    1.000000E-03    7.427210E-06         505      1528         0         1
    4.957530E-01    1.000000E-03    2.140683E-05         605      1828         0         1
    5.957530E-01    1.000000E-03    1.021641E-10         705      2129         0         1
    6.912530E-01    5.000000E-04    1.296611E-05         806      2434         0         2
    7.857530E-01    5.000000E-04    2.892574E-05         908      2744         0         3
    8.792530E-01    1.000000E-03    3.699678E-19        1009      3047         0         4
    9.737530E-01    1.000000E-03    1.027208E-04        1111      3354         0         5
    1.000000E+00    4.940000E-04    6.307386E-06        1138      3435         0         5

_________________________________________________________________________________________________
Analysis Time Information
    Starting Time/Date     = 21:34:21 / 2026.6.10
    Ending Time/Date       = 21:35:3 / 2026.6.10
    CPU Time = 42.8 Second (0 hr. 0 min 42.8 sec.)

_________________________________________________________________________________________________
Analysis is accomplished successfully

_________________________________________________________________________________________________
