__________________________________________________________________________________________________
RecurDyn2023 [Windows x64 System 10.1.11516.0] Analysis message file.
Copyright (C) 1997 - 2022 FunctionBay, Inc. All rights reserved.

RMD file: Hollow cylinder - Cylinder - Frictional contact.rmd [Model Name: Model1]

_________________________________________________________________________________________________
System Configuration Information
    No. of Generalized Coordinate                   = 2
    No. of Generalized Velocity                     = 2
    No. of Rigid Body                               = 2
    No. of Geo Contact                              = 1

Kinematic Degree of Freedom         = 1

Total array size                    = 4243
Total memory size for array         = 0 MB

Success Process: Array Structure Construction

_________________________________________________________________________________________________
Redundant Constraint Information
    There is no redundant constraint

_________________________________________________________________________________________________
RecurDyn/SOLVER Information
    DLL type Solver for Windows 64 Bit
    No. of CPU Thread = 4
    Save Solver Animation File(RAN) Option is turned on
    C:\Program Files\FunctionBay, Inc\RecurDyn 2023\Bin\Solver\Slvcore.dll
    C:\Program Files\FunctionBay, Inc\RecurDyn 2023\Bin\Solver\Cuser.dll

_________________________________________________________________________________________________
Analysis Information
    Dynamic Analysis
    End Time                       = 1.000000000000000
    Step                           = 1000
    Plot Multiplier Step Factor    = 1
    Maximum Time Step              = 1.0E-03
    Initial Time Step              = 1.0E-06
    Error Tolerance                = 5.0E-03

_________________________________________________________________________________________________
Information of starting time
    Starting Time/Date     = 17:24:56 / 2026.6.13

_________________________________________________________________________________________________
Integrator Information
     Advanced Hybrid Implicit Integrator :: LDLT
        Numerical Damping          = 1.000000
        Linear Solver For MBD      = DENSE

_________________________________________________________________________________________________
Analysis processing...

        TIME          STEPSIZE        A_DELNRM          NJAC      NRES      ANRF     AINTF
    6.133000E-03    5.120000E-04    1.622270E-03         102       311         0         0
    1.012530E-01    1.000000E-03    8.077307E-16         202       611         0         0
    2.012530E-01    1.000000E-03    1.430871E-14         302       911         0         0
    3.012530E-01    1.000000E-03    3.993651E-15         402      1211         0         0
    4.012530E-01    1.000000E-03    6.686708E-15         502      1511         0         0
    5.012530E-01    1.000000E-03    5.973133E-15         602      1811         0         0
    6.012530E-01    1.000000E-03    1.735657E-14         702      2111         0         0
    7.012530E-01    1.000000E-03    1.110130E-15         802      2411         0         0
    8.012530E-01    1.000000E-03    1.049821E-14         902      2711         0         0
    9.012530E-01    1.000000E-03    3.028921E-14        1002      3011         0         0
    1.000000E+00    7.470000E-04    7.203531E-16        1101      3308         0         0

_________________________________________________________________________________________________
Analysis Time Information
    Starting Time/Date     = 17:24:56 / 2026.6.13
    Ending Time/Date       = 17:30:13 / 2026.6.13
    CPU Time = 317.88 Second (0 hr. 5 min 17.88 sec.)

_________________________________________________________________________________________________
Analysis is accomplished successfully

_________________________________________________________________________________________________
