__________________________________________________________________________________________________
RecurDyn2023 [Windows x64 System 10.1.11516.0] Analysis message file.
Copyright (C) 1997 - 2022 FunctionBay, Inc. All rights reserved.

RMD file: First-stage gear transmission.rmd [Model Name: Model2]

_________________________________________________________________________________________________
System Configuration Information
    No. of Generalized Coordinate                   = 2
    No. of Generalized Velocity                     = 2
    No. of Rigid Body                               = 2
    No. of Geo Contact                              = 1

Kinematic Degree of Freedom         = 1

Total array size                    = 3809
Total memory size for array         = 0 MB

Success Process: Array Structure Construction

_________________________________________________________________________________________________
Redundant Constraint Information
    There is no redundant constraint

_________________________________________________________________________________________________
RecurDyn/SOLVER Information
    DLL type Solver for Windows 64 Bit
    No. of CPU Thread = 4
    Save Solver Animation File(RAN) Option is turned on
    C:\Program Files\FunctionBay, Inc\RecurDyn 2023\Bin\Solver\Slvcore.dll
    C:\Program Files\FunctionBay, Inc\RecurDyn 2023\Bin\Solver\Cuser.dll

_________________________________________________________________________________________________
Analysis Information
    Dynamic Analysis
    End Time                       = 1.000000000000000
    Step                           = 1000
    Plot Multiplier Step Factor    = 1
    Maximum Time Step              = 1.0E-03
    Initial Time Step              = 1.0E-06
    Error Tolerance                = 5.0E-03

_________________________________________________________________________________________________
Information of starting time
    Starting Time/Date     = 21:33:46 / 2026.6.10

_________________________________________________________________________________________________
Integrator Information
     Advanced Hybrid Implicit Integrator :: LDLT
        Numerical Damping          = 1.000000
        Linear Solver For MBD      = DENSE

_________________________________________________________________________________________________
Analysis processing...

        TIME          STEPSIZE        A_DELNRM          NJAC      NRES      ANRF     AINTF
    6.133000E-03    5.120000E-04    4.313791E-05         101       304         0         0
    9.250300E-02    2.500000E-04    4.441948E-05         204       614         0         2
    1.815030E-01    1.000000E-03    4.860458E-02         307       929         0         3
    2.625030E-01    5.000000E-04    5.091329E-04         415      1265         1         6
    3.595030E-01    1.000000E-03    3.491191E-05         515      1569         1         6
    4.595030E-01    1.000000E-03    1.316670E-03         615      1870         1         6
    5.595030E-01    1.000000E-03    1.002092E-11         715      2171         1         6
    6.595030E-01    1.000000E-03    4.230640E-06         815      2475         1         6
    7.540030E-01    1.000000E-03    1.155141E-07         917      2784         1         7
    8.540030E-01    1.000000E-03    5.601729E-12        1017      3087         1         7
    9.540030E-01    1.000000E-03    9.891563E-21        1118      3392         1         7
    1.000000E+00    9.970000E-04    0.000000E+00        1164      3530         1         7

_________________________________________________________________________________________________
Analysis Time Information
    Starting Time/Date     = 21:33:46 / 2026.6.10
    Ending Time/Date       = 21:33:47 / 2026.6.10
    CPU Time = 1.44 Second (0 hr. 0 min 1.44 sec.)

_________________________________________________________________________________________________
Analysis is accomplished successfully

_________________________________________________________________________________________________
