#!/usr/bin/env python3
"""Generate OBJ meshes for SDF contact validation.

Constraints:
  - Longest edge ≤ 0.2
  - Cube half-width ≥ 2.0  (full side ≥ 4.0)
  - Hollow cylinder: bottom annular face (contact patch), R_i=0.4, R_o=0.6
"""

import numpy as np
import os

def _write_obj(path, vertices, faces):
    with open(path, 'w') as f:
        f.write(f"# {os.path.basename(path)}\n")
        f.write(f"# vertices: {len(vertices)}, triangles: {len(faces)}\n")
        f.write("# generated by gen_meshes.py\n")
        f.write("o object\n")
        for v in vertices:
            f.write(f"v {v[0]:.10f} {v[1]:.10f} {v[2]:.10f}\n")
        for tri in faces:
            f.write(f"f {tri[0]+1} {tri[1]+1} {tri[2]+1}\n")

def _check_max_edge(vertices, faces, label):
    max_len = 0.0
    for tri in faces:
        v0, v1, v2 = vertices[tri]
        for a, b in [(v0,v1),(v1,v2),(v2,v0)]:
            l = np.linalg.norm(a - b)
            if l > max_len:
                max_len = l
    ok = max_len <= 0.201
    print(f"  {label}: max edge = {max_len:.4f}  {'OK' if ok else 'WARNING'}")
    return max_len

def generate_cube(path, half_width=2.0, max_edge=0.2):
    spacing = max_edge / np.sqrt(2)
    n = max(int(np.ceil(2 * half_width / spacing)), 2)
    print(f"Cube: half_width={half_width}, segments={n}")

    verts = []
    faces = []
    for axis, sign, u_axis, v_axis in [
        (0, -1, 1, 2), (0, 1, 1, 2),
        (1, -1, 0, 2), (1, 1, 0, 2),
        (2, -1, 0, 1), (2, 1, 0, 1)
    ]:
        base = len(verts)
        for i in range(n + 1):
            for j in range(n + 1):
                p = [0.0, 0.0, 0.0]
                p[axis] = sign * half_width
                u = -half_width + 2 * half_width * i / n
                v = -half_width + 2 * half_width * j / n
                p[u_axis] = u
                p[v_axis] = v
                verts.append(p)
        for i in range(n):
            for j in range(n):
                i0 = base + i * (n + 1) + j
                i1 = i0 + 1
                i2 = i0 + (n + 1)
                i3 = i2 + 1
                if sign == 1:
                    faces.append([i0, i2, i1])
                    faces.append([i1, i2, i3])
                else:
                    faces.append([i0, i1, i2])
                    faces.append([i1, i3, i2])

    verts = np.array(verts)
    verts[:, 2] -= half_width
    faces = np.array(faces)
    _write_obj(path, verts, faces)
    _check_max_edge(verts, faces, "cube")
    print(f"  -> {len(verts)} verts, {len(faces)} tris")
    return verts, faces

def generate_hollow_cylinder(path, R_i=0.4, R_o=0.6, height=0.5,
                              n_az=27, n_rad=2, n_vert=4):
    print(f"Hollow cylinder ({os.path.basename(path)}): "
          f"n_az={n_az}, n_rad={n_rad}, n_vert={n_vert}")

    verts = []
    faces = []

    def add_cylindrical_surface(r, flip=False):
        base = len(verts)
        for k in range(n_vert + 1):
            z = k * height / n_vert
            for j in range(n_az):
                theta = j * 2 * np.pi / n_az
                x = r * np.cos(theta)
                y = r * np.sin(theta)
                verts.append([x, y, z])
        for k in range(n_vert):
            for j in range(n_az):
                j1 = (j + 1) % n_az
                i0 = base + k * n_az + j
                i1 = base + k * n_az + j1
                i2 = base + (k + 1) * n_az + j
                i3 = base + (k + 1) * n_az + j1
                if flip:
                    faces.append([i0, i2, i1])
                    faces.append([i1, i2, i3])
                else:
                    faces.append([i0, i1, i2])
                    faces.append([i1, i3, i2])

    add_cylindrical_surface(R_i, flip=True)
    add_cylindrical_surface(R_o, flip=False)

    def add_annular_face(z, flip=False):
        base = len(verts)
        for j in range(n_az):
            for i in range(n_rad + 1):
                r = R_i + i * (R_o - R_i) / n_rad
                theta = j * 2 * np.pi / n_az
                x = r * np.cos(theta)
                y = r * np.sin(theta)
                verts.append([x, y, z])
        for j in range(n_az):
            j1 = (j + 1) % n_az
            for i in range(n_rad):
                i0 = base + j * (n_rad + 1) + i
                i1 = i0 + 1
                i2 = base + j1 * (n_rad + 1) + i
                i3 = i2 + 1
                if flip:
                    faces.append([i0, i2, i1])
                    faces.append([i1, i2, i3])
                else:
                    faces.append([i0, i1, i2])
                    faces.append([i1, i3, i2])

    add_annular_face(0.0, flip=True)
    add_annular_face(height, flip=False)

    verts = np.array(verts)
    faces = np.array(faces)
    _write_obj(path, verts, faces)
    _check_max_edge(verts, faces, "hollow_cylinder")
    print(f"  -> {len(verts)} verts, {len(faces)} tris")
    return verts, faces


# ---- density presets: (label, n_az, n_rad, n_vert, max_edge_target) ----
CYLINDER_PRESETS = [
    ("coarse",   12, 1, 2, 0.4),
    ("medium",   20, 2, 3, 0.25),
    ("fine",     27, 2, 4, 0.2),    # matches original constraint
    ("dense",    40, 3, 6, 0.12),
    ("very_dense", 60, 4, 10, 0.08),
]


if __name__ == '__main__':
    out_dir = os.path.join(os.path.dirname(__file__), '..', 'models')
    os.makedirs(out_dir, exist_ok=True)

    print("=" * 60)
    print("Generating OBJ meshes for SDF contact validation")
    print("=" * 60)

    # --- Cube (single density) ---
    print("\n--- Cube ---")
    generate_cube(os.path.join(out_dir, 'cube.obj'))

    # --- Hollow cylinder (multiple densities) ---
    print("\n--- Hollow cylinder variants ---")
    for label, n_az, n_rad, n_vert, target in CYLINDER_PRESETS:
        fname = f"hollow_cylinder_{label}.obj"
        generate_hollow_cylinder(
            os.path.join(out_dir, fname),
            n_az=n_az, n_rad=n_rad, n_vert=n_vert)

    print(f"\nDone. {len(CYLINDER_PRESETS)} cylinder variants saved to: {out_dir}")
