__________________________________________________________________________________________________
RecurDyn2023 [Windows x64 System 10.1.11516.0] Analysis message file.
Copyright (C) 1997 - 2022 FunctionBay, Inc. All rights reserved.

RMD file: First-stage gear transmission.rmd [Model Name: Model2]

_________________________________________________________________________________________________
System Configuration Information
    No. of Generalized Coordinate                   = 2
    No. of Generalized Velocity                     = 2
    No. of Rigid Body                               = 2
    No. of Geo Contact                              = 1

Kinematic Degree of Freedom         = 1

Total array size                    = 3809
Total memory size for array         = 0 MB

Success Process: Array Structure Construction

_________________________________________________________________________________________________
Redundant Constraint Information
    There is no redundant constraint

_________________________________________________________________________________________________
RecurDyn/SOLVER Information
    DLL type Solver for Windows 64 Bit
    No. of CPU Thread = 4
    Save Solver Animation File(RAN) Option is turned on
    C:\Program Files\FunctionBay, Inc\RecurDyn 2023\Bin\Solver\Slvcore.dll
    C:\Program Files\FunctionBay, Inc\RecurDyn 2023\Bin\Solver\Cuser.dll

_________________________________________________________________________________________________
Analysis Information
    Dynamic Analysis
    End Time                       = 1.000000000000000
    Step                           = 1000
    Plot Multiplier Step Factor    = 1
    Maximum Time Step              = 1.0E-03
    Initial Time Step              = 1.0E-06
    Error Tolerance                = 5.0E-03

_________________________________________________________________________________________________
Information of starting time
    Starting Time/Date     = 21:35:38 / 2026.6.10

_________________________________________________________________________________________________
Integrator Information
     Advanced Hybrid Implicit Integrator :: LDLT
        Numerical Damping          = 1.000000
        Linear Solver For MBD      = DENSE

_________________________________________________________________________________________________
Analysis processing...

        TIME          STEPSIZE        A_DELNRM          NJAC      NRES      ANRF     AINTF
    3.093000E-03    6.400000E-05    1.407796E-05         104       319         1         1
    6.696100E-02    1.000000E-03    6.347053E-06         206       626         1         2
    1.559610E-01    1.000000E-03    1.206896E-06         313       955         2         3
    2.559610E-01    1.000000E-03    3.971709E-08         415      1265         2         3
    3.559610E-01    1.000000E-03    7.401216E-06         516      1576         2         3
    4.449610E-01    1.000000E-03    1.876427E-04         623      1906         2         5
    5.394610E-01    1.000000E-03    8.941412E-07         727      2220         2         6
    6.069610E-01    5.000000E-04    1.859919E-08         833      2535         2        11
    6.789610E-01    1.000000E-03    1.552282E-04         939      2853         2        15
    7.679610E-01    1.000000E-03    3.837416E-19        1044      3169         2        17
    8.679610E-01    1.000000E-03    1.047450E-08        1144      3473         2        17
    9.624610E-01    1.000000E-03    4.588656E-07        1247      3786         2        18
    1.000000E+00    3.900000E-05    1.596593E-12        1293      3924         2        19

_________________________________________________________________________________________________
Analysis Time Information
    Starting Time/Date     = 21:35:38 / 2026.6.10
    Ending Time/Date       = 21:36:26 / 2026.6.10
    CPU Time = 48.8 Second (0 hr. 0 min 48.8 sec.)

_________________________________________________________________________________________________
Analysis is accomplished successfully

_________________________________________________________________________________________________
